spring:
  sql:
    init:
      mode: always
      schema-locations: ""
  application:
    name: TestGraphQl
  datasource:
    url: jdbc:postgresql://localhost:5432/animals
    username: postgres
    password: 12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      schema: graphqltest
      connection-init-sql: CREATE SCHEMA if not exists "graphqltest";
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
      path: /graphiql