spring:
  sql:
    init:
      mode: always
      schema-locations: ""
  application:
    name: HW-15
  datasource:
    url: jdbc:postgresql://localhost:5432/animals
    username: postgres
    password: 12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      schema: animals
      connection-init-sql: CREATE SCHEMA if not exists "animals";
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    default-schema: animals

