spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  application:
    name: HW-18
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_security
    username: postgres
    password: 12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      schema: db_security
      #connection-init-sql: CREATE SCHEMA if not exists "db_security";
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.xml
    default-schema: db_security
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
server:
  port: 8090